[package]
name = "aleo-prover"
version = "0.2.7"
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#snarkvm = { path = "../../src/snarkVM" }
#snarkvm = { git = "https://github.com/HarukaMa/snarkVM.git", rev = "3ffd025b" }
snarkvm = { git = "https://github.com/AleoHQ/snarkVM.git", rev = "e0462bf" }

#snarkos = { path = "../../src/snarkOS" }
#snarkos = { git = "https://github.com/HarukaMa/snarkOS.git", rev = "1b18de2e" }
snarkos = { git = "https://github.com/AleoHQ/snarkOS.git"}

#snarkos-storage = { path = "../../src/snarkOS/storage" }
#snarkos-storage = { git = "https://github.com/HarukaMa/snarkOS.git", rev = "1b18de2e" }
snarkos-storage = { git = "https://github.com/AleoHQ/snarkOS.git"}

rand = "0.8.4"
num_cpus = "1.13.1"
structopt = "0.3.25"
rayon = "1.5.1"
anyhow = "1.0.53"
tracing = "0.1.29"
tracing-subscriber = "0.3.6"
tokio-util = "0.6.9"
tokio-stream = "0.1.8"
futures-util = "0.3.19"
crossbeam = "0.8.1"
futures = "0.3.19"
serde_json = "1.0.74"

[dependencies.tokio]
version = "1.15.0"
features = [
    "rt-multi-thread",
    "macros",
    "sync",
]

[features]
enable-cuda = ["snarkvm/cuda"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
